version: '3.8'

services:
  finance-api:
    image: openjdk:21-jdk
    container_name: finance-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${render_database_host}:5432/finance_db_gnw3
      SPRING_DATASOURCE_USERNAME: ${render_database_user}
      SPRING_DATASOURCE_PASSWORD: ${render_database_password}
    ports:
      - "8080:8080"
    volumes:
      - ./target/finance-api-0.0.1-SNAPSHOT.jar:/app/finance-api.jar
    command: ["java", "-jar", "/app/finance-api.jar"]
