version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  finance-api:
    image: openjdk:21-jdk
    container_name: finance-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    volumes:
      - ./target/finance-api-0.0.1-SNAPSHOT.jar:/app/finance-api.jar
    command: ["java", "-jar", "/app/finance-api.jar"]

volumes:
  postgres-data:
