version: '3.8'

services:
  mongo:
    image: mongo:5.0.1
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - finance-network

  finance-api:
    image: openjdk:21-jdk
    container_name: finance-api
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@localhost:27017/finance_db
    ports:
      - "8080:8080"
    volumes:
      - ./target/finance-api.jar:/app/finance-api.jar
    command: ["java", "-jar", "/app/finance-api.jar"]
    networks:
      - finance-network

volumes:
  mongo-data:

networks:
  finance-network:
    driver: bridge
